-- https://github.com/L3MON4D3/LuaSnip/blob/b5a72f1fbde545be101fcd10b70bcd51ea4367de/Examples/snippets.lua#L501
-- require('luasnip.loaders.from_vscode').load({ include = {
--   "javascriptreact",
--   "typescriptreact",
--   "javascript",
--   "typescript",
--   "css",
--   "html",
-- }})
